name: "clean up"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 1 * *'  
  
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    name: clean up
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: master # 改成存放图片的分支
    - name: commit
      run: |
        git config --global user.name "horrordor"
        git config --global user.email "cccccc2002@outlook.com"
        git checkout --orphan fuck
        git add -A && echo "Git Added" 
        git branch -D master
        git commit -a -m "clean up"
        git branch -m master
        git push -f origin master
    - name: Failure test
      if: failure()
      run: | 
        ls -R
        echo "Error on running!"
